general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 16

[font.offset]
x = 0
y = 1

[window]
# padding.x = 10
# padding.y = 14
dynamic_padding = true
decorations = "None"
opacity = 0.3

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" }
]
